[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit_withdraw_solana_program = "4K7D7cDzpnGdKKFQhAP6TPLFnKkeVqVPkjRgggNHsd7C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
